Solana pay [Reference]
solana-developers/solana-cookbook pull request #297
Opened 2022-03-28 18:36 UTC by 0xPratik

2022-03-30 19:45 UTC, 0xPratik commented
Hey @jacobcreech do you think there should be an instruction on how to setup Point of Sale Application in the cookbook

2022-03-31 07:28 UTC, jacobcreech commented
The PoS app tutorial could be completely separate and should probably lie outside of the cookbook as a standalone tutorial

2022-04-01 19:23 UTC, jacobcreech requested changes
A few changes. We may want to also move this over to `Integrations` instead of the main page of cookbook references.

2022-04-01 19:23 UTC, jacobcreech commented on docs/.vuepress/config.ts
> -import { defineUserConfig } from 'vuepress';
Could you remove the reformatting?

2022-04-01 19:23 UTC, jacobcreech commented on docs/references/solana-pay.md
> +**@solana/pay** is a JavaScript library for facilitating commerce on Solana by using a token transfer URL scheme. The URL scheme ensures that no matter the wallet or service used, the payment request
Could we link the [scheme](https://docs.solanapay.com/spec) here?

2022-04-01 19:23 UTC, jacobcreech commented on docs/references/solana-pay.md
> +In this Code-snippet we are going to look into how create a payment request URL and encode it into a QR Code
```suggestion
To create a SOL payment request, we first generate a QR code with a payment request URI.
```

2022-04-01 19:23 UTC, jacobcreech commented on docs/references/solana-pay.md
> +In this Code-snippet we are going to look into how create a payment request for a user who can transfer tokens of a specific mint accepted by the merchant.
```suggestion
To create a payment request using a custom token other than Native SOL, you can specify the mint address in the payment request URL.
```

2022-04-01 19:23 UTC, jacobcreech commented on docs/references/solana-pay.md
> +      content: Learn how to write programs on Solana, with references on cross program invocation, reading accounts, and more
I don't think this `og:description` matches what is on the page.

2022-04-01 19:23 UTC, jacobcreech commented on docs/references/solana-pay.md
> +      content: Solana Cookbook | Solana Pay Reference
```suggestion
      content: Solana Cookbook | Solana Pay
```

2022-04-01 19:23 UTC, jacobcreech commented on docs/references/solana-pay.md
> +      content: Solana Cookbook | Solana Pay Reference
```suggestion
      content: Solana Cookbook | Solana Pay
```

2022-04-04 18:55 UTC, 0xPratik commented
Hey @jacobcreech I have done the requested changes according to the review. Should we move this section to integrations currently it's in references

2022-04-05 20:34 UTC, 0xPratik commented
Hello @jacobcreech I have moved the Solana Pay section to integrations

2022-04-11 18:55 UTC, jacobcreech commented
@0xPratik If you're leaving in all of the format changes on the config, could you also add whatever prettier or lint config you have? Would fall under #280

2022-04-11 18:59 UTC, 0xPratik commented
Sure Ser Will add that as well and I was thinking of adding a section of transaction request's as well in the Solana Pay integration section once it gets merged in the master branch of Solana pay or Should i add it later in a different PR

2022-04-11 19:00 UTC, jacobcreech commented
@0xPratik a different PR for transaction request would be fine

2022-05-29 05:27 UTC, 0xPratik commented
Hey @jacobcreech can you please review this PR

2024-01-07 17:35 UTC, closed without merging