feat: add read multiple instructions snippet
solana-developers/solana-cookbook pull request #321
Opened 2022-04-14 23:10 UTC by migui3230

2022-04-18 20:43 UTC, jacobcreech commented
@migui3230 Could you make the full source the actual program code? Want to be able to deploy this example if needed

2022-04-18 20:44 UTC, jacobcreech requested changes
A few changes + Full code requested

2022-04-18 20:44 UTC, jacobcreech commented on docs/references/programs.md
> +3. Check for errors within the loop
Let's remove this

2022-04-18 20:44 UTC, jacobcreech commented on docs/references/programs.md
> +Since Solana allows us to take a peek at all of the instructions in the current transaction. We can store them in a variable and
```suggestion
Solana allows us to take a peek at all of the instructions in the current transaction. We can store them in a variable and 
```

2022-04-21 21:24 UTC, jacobcreech commented
@migui3230 Where is the actual code that inspects the instructions on the transaction in the program? I'm expecting to see something like 

```rust
let num_instructions = read_u16(&mut idx, &instruction_sysvar)
            .map_err(|_| ProgramError::InvalidAccountData)?;
```

and then iterating through those in the program. That would be the entire preview

2022-04-22 17:47 UTC, migui3230 commented
Gotcha, I understand now. Sorry for the confusion!

2022-04-26 00:17 UTC, migui3230 commented
@jacobcreech pushed changes im pretty sure this is what you're looking for?

2022-05-05 15:12 UTC, merged