French Translation for Solana Cookbook
solana-developers/solana-cookbook pull request #458
Opened 2022-10-01 12:48 UTC by cryptoloutre

This PR can resolve #451

2022-10-04 23:06 UTC, mwrites commented
Hello @cryptoloutre, je vais être le reviewer pour cette PR :)

2022-10-05 00:44 UTC, mwrites requested changes
Énorme travail, au nom des français merci ! 🥖

Overall notbig issues, aside from feature-parity-testing which is a bit confusing because of the choice of words. Maybe because of machine translation?

2022-10-05 00:44 UTC, mwrites commented on docs/fr/guides/feature-parity-testing.md
> +title: Test de Conformité des Caractéristiques
Il semble qu'il y ait une confusion entre caractéristiques et fonctionnalités.

En gros, chaque changement sur le code des validateurs est déployé sous forme de `fonctionnalité`. Ces fonctionnalités sont déployées graduellement et nécessitent d'être activées. D'où la nécessité de tester si une fonctionnalité est active ou non sur un validateur.

2022-10-05 00:44 UTC, mwrites commented on docs/fr/guides/serialization.md
> +Nous avons montré comment créer des chargements simples dans les exemples précédents. Parfois Solana lance une balle rapide avec certains types. Cette section montrera le mappage approprié entre TS/J
On peut supprimer "Parfois Solana lance une balle rapide avec certains types."

2022-10-05 00:44 UTC, mwrites commented on docs/fr/references/programs.md
> +Puisque les programmes dans Solana sont sans état, nous, en tant que créateur de programme, devons nous assurer que les comptes passés sont valides autant que possible pour éviter toute entrée de com
Ainsi, les contrôles

2022-10-05 00:44 UTC, mwrites commented on docs/fr/references/name-service.md
> +title: Service des Noms
"Service de Noms" (similaire à _système de noms de domaine_)

2022-10-05 08:40 UTC, cryptoloutre commented
Hey @mwrites :)

Il n'y a pas de soucis, c'est un plaisir de pouvoir contribuer à mon échelle au Solana Cookbook ^^
Je viens de faire les modifications suggérées par tes remarques

2022-10-05 14:02 UTC, mwrites commented
> Hey @mwrites :)
> 
> Il n'y a pas de soucis, c'est un plaisir de pouvoir contribuer à mon échelle au Solana Cookbook ^^ Je viens de faire les modifications suggérées par tes remarques

Super !

2022-10-05 14:03 UTC, mwrites approved these changes

2022-10-05 14:05 UTC, mwrites commented
@jacobcreech good to go!

2022-10-05 14:09 UTC, merged