feat(examples): candy machine code examples
solana-developers/solana-cookbook pull request #474
Opened 2022-10-31 18:41 UTC by 0xMukesh

- Closes #473

2022-10-31 18:56 UTC, 0xMukesh commented
Weird, I can't see the "Candy Machine v2" header under the NFTs reference section

| [Vercel preview](https://solana-cookbook-git-fork-0xmukesh-feat-candy-d80f9e-solana-labs.vercel.app/references/nfts.html) | Local development environment |
| -------------------------------------------------------------------------------------------------------------------------------- | ---------------------------------- |
| ![image](https://user-images.githubusercontent.com/90365542/199086322-e31899aa-a2fe-4ce9-9f6b-dbfcd537b575.png)  | ![image](https://user-images.githubusercontent.com/90365542/199087366-64101568-93f1-458a-baed-dfe3f6923cb6.png)

2022-11-01 02:47 UTC, jacobcreech requested changes
Awesome work! Just a few requested changes to help improve SEO

2022-11-01 02:47 UTC, jacobcreech commented on docs/references/nfts.md
> +### How to find minted NFTs
```suggestion
### How to find minted NFTs from a Candy Machine
```

2022-11-01 02:47 UTC, jacobcreech commented on docs/references/nfts.md
> +### How to insert items
```suggestion
### How to insert items into a Candy Machine
```

2022-11-01 02:47 UTC, jacobcreech commented on docs/references/nfts.md
> +### How to mint an NFT
```suggestion
### How to mint an NFT from a Candy Machine
```

2022-11-01 06:30 UTC, jacobcreech approved these changes

2022-11-01 06:30 UTC, merged

2022-11-01 07:25 UTC, 0xMukesh commented
Hey @jacobcreech, thank you for merging the PR. Have checked the [production site](https://solanacookbook.com) and it can't see the "Candy Machine v2" header under the NFTs reference section. Did I miss something to change in vuepress's configuration or anything else?

2022-11-01 14:48 UTC, jacobcreech commented
@0xMukesh Unfortunately I temporarily disabled the build because vercel can't handle building so many pages of vuepress at once. Going to have to manually build and push until I get a better CICD pipeline